language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-22
    - extra-android-m2repository

  script:
    - ./gradlew clean testDebugUnitTest
    - ./gradlew test --continue
